# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fuzmit < Formula
  desc "Conventional commits with fuzzy type selection and direct CLI flags"
  homepage "https://github.com/o6uoq/fuzmit"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/o6uoq/fuzmit/releases/download/v0.1.2/fuzmit_0.1.2_darwin_amd64.tar.gz"
      sha256 "f399346ffa071a63b1fa7ec8a2062acfc0bdd08f8cbceae3a1da5fb436cd955d"

      define_method(:install) do
        bin.install "fuzmit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/o6uoq/fuzmit/releases/download/v0.1.2/fuzmit_0.1.2_darwin_arm64.tar.gz"
      sha256 "be6b30ca758fedfbe1f75c558fca44962f14abb6171ed0d3dac702dc51edbefa"

      define_method(:install) do
        bin.install "fuzmit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/o6uoq/fuzmit/releases/download/v0.1.2/fuzmit_0.1.2_linux_amd64.tar.gz"
      sha256 "3c28e051fd88f4bbab1685a9441eb09d93bc4f9953593d28bb38b8c625739da0"
      define_method(:install) do
        bin.install "fuzmit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/o6uoq/fuzmit/releases/download/v0.1.2/fuzmit_0.1.2_linux_arm64.tar.gz"
      sha256 "38fa508019a041043ca79141e6e71de2ef584d6b60d5f682adffddc68df0f882"
      define_method(:install) do
        bin.install "fuzmit"
      end
    end
  end

  test do
    system "#{bin}/fuzmit", "--help"
  end
end
