# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fuzmit < Formula
  desc "Conventional commits with fuzzy type selection and direct CLI flags"
  homepage "https://github.com/o6uoq/fuzmit"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/o6uoq/fuzmit/releases/download/v0.1.0/fuzmit_0.1.0_darwin_amd64.tar.gz"
      sha256 "56ef82427e4421ff1809da1155b6d09908475ae99ab16f92fa8e0dc830cb7c68"

      define_method(:install) do
        bin.install "fuzmit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/o6uoq/fuzmit/releases/download/v0.1.0/fuzmit_0.1.0_darwin_arm64.tar.gz"
      sha256 "9bcefce797bb78f43d68bca7379491053496e77f6cf1837e69048c95a7bba2f4"

      define_method(:install) do
        bin.install "fuzmit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/o6uoq/fuzmit/releases/download/v0.1.0/fuzmit_0.1.0_linux_amd64.tar.gz"
      sha256 "5dbb8b8c29f8c986f94ee6f759927e183a82f062edd7c957b5f37c9feb0b77a7"
      define_method(:install) do
        bin.install "fuzmit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/o6uoq/fuzmit/releases/download/v0.1.0/fuzmit_0.1.0_linux_arm64.tar.gz"
      sha256 "eeb2f2630060fda805ca355e68a349da57bd779053ea0b9084968c577ecb4431"
      define_method(:install) do
        bin.install "fuzmit"
      end
    end
  end

  test do
    system "#{bin}/fuzmit", "--help"
  end
end
